### ISSUE TITLE
Add WishlistSyncInterface to every messenger handled message

### ISSUE THREAD

**Issue by oliver-schulz** [BitBagCommerce/SyliusWishlistPlugin#219]
I'am using the version 4.0 of this Plugin. 

In our project every transport is async by default. So every action i make with wishlists is also async after installing the plugin. When creating a new wishlist i will get an error because the message was not handled in `sync`. Which also makes totally sense.

In my messenger configuration i had to configure the following, in order to get every single `SyliusWishlistPlugin` message handled by a `sync` transport.

```
framework:
  messenger:
    transports:
      sync:
        dsn: 'sync://'
    routing:
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\RemoveWishlist': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\RemoveProductVariantFromWishlist': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\RemoveProductFromWishlist': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\UpdateWishlistNameInterface': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\RemoveSelectedProductsFromWishlist': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\ExportSelectedProductsFromWishlistToPdfInterface': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\AddWishlistToUser': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\CopySelectedProductsToOtherWishlistInterface': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\AddSelectedProductsToCart': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\CreateNewWishlist': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\CreateWishlist': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\AddProductToSelectedWishlist': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\AddProductsToCartInterface': sync
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\WishlistTokenValueAwareInterface': sync
```

My idea here is to minimize the configuration by adding a `WishlistSyncInterface` to every messenger relevant command. And also adding a hint to the documentation that when you are using async transports only, you have to configure your messenger like this:

```
framework:
  messenger:
    transports:
      sync:
        dsn: 'sync://'
    routing:
      'BitBag\SyliusWishlistPlugin\Command\Wishlist\WishlistSyncInterface': sync
```

**Comment by senghe** [comment]
Hi @oliver-schulz, thanks for the issue! :) I've prepared a PR for your idea. It passed the build, but I'm waiting currently for code review from our team, before it'll be merged.

Cheers! :)

**Comment by senghe** [comment]
It's merged :tada:

**Comment by oliver-schulz** [comment]
Thx, this worked great!

For the docs:
```
framework:
  messenger:
    transports:
      sync:
        dsn: 'sync://'
    routing:
      BitBag\SyliusWishlistPlugin\Command\Wishlist\WishlistSyncCommandInterface: sync
```
