### ISSUE TITLE
WishlistProduct resource gets an incorrect controller class

### ISSUE THREAD

**Issue by er1z** [BitBagCommerce/SyliusWishlistPlugin#54]
If you try, to create a resource route with standard `ResourceController` for `wishlist_product`, you end up with an error of non-existing method.

Got dug into the code and found that the default controller is — probably accidentally — specified as one of `EntityRepository` aliases.

![image](https://user-images.githubusercontent.com/1813302/116394452-34515800-a823-11eb-9fdb-24b811c78f1e.png)

A workaround:
```
bit_bag_sylius_wishlist:
    resources:
        wishlist_product:
            classes:
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
```
